### ISSUE TITLE
Integrate unit tests

### ISSUE THREAD

**Issue by rhiever** [rhiever/datacleaner#5]
Test both autoclean() and autoclean_cv(), each with 5 test cases:

1) Simulated data, no NaNs, all columns numerical

2) Simulated data, with NaNs, all columns numerical

3) Simulated data, no NaNs, some columns with strings

4) Simulated data, with NaNs, some columns with strings

5) Real data (adult.csv.gz) with some NaNs placed into it

**Comment by myselfHimanshu** [comment]
I simulated a data with NaNs, all columns numerical. 
I have 'Age' as a feature in dataset which is continuous variable, so we should use the median for continuous variables. 
But running the script with autoclean() , the missing values are filled with the mode of the column.

**Comment by rhiever** [comment]
Can you please share the data or the code that generated that data?

**Comment by myselfHimanshu** [comment]
I have attached the code(Datacleaner.py) and dataset(test.csv).
[dataclean.zip](https://github.com/rhiever/datacleaner/files/159655/dataclean.zip)

**Comment by rhiever** [comment]
@myselfHimanshu, please give the latest version (datacleaner-0.1.4) a try and see if that has corrected your issue. While building the unit tests, I found a bug in the software and have since corrected it in the latest release. You can get the latest version of datacleaner with the following command:

```
pip install --upgrade datacleaner
```
